name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Pytest
      run: |
        pytest
    - name: Lint with Pylint
      run: |
        pylint D:\a_STUDIA\6 semestr\praktyka programowania\pp\praktyka_programowania_ci_cd\utils.py
    - name: Format with Black
      run: |
        black --check .
